package MesBeans;
// Generated 13 d�c. 2022 08:52:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="userbdd"
)
public class Users  implements java.io.Serializable {


     private String username;
     private String password;

    public Users() {
    }

    public Users(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


